name: build images

on:
  push:
    branches: [ "main" ]
    tags-ignore: [ "*" ]

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  php:
    runs-on: ubuntu-latest
    name: build base image for php
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      name: login to ghcr.io
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v3
      with:
        context: ./php
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/hugofruit/php,ghcr.io/${{ github.repository_owner }}/hugofruit/php:8.1
    - uses: aquasecurity/trivy-action@master
      name: run Trivy vulnerability scanner
      with:
        image-ref: "ghcr.io/${{ github.repository_owner }}/hugofruit/php"
        format: 'template'
        template: '@/contrib/sarif.tpl'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'
    - name: upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'
